#pragma once

typedef enum
{
    FLOCK_CMD_DEVICE_INFO = 0x1,
    FLOCK_CMD_GET_FREQ = 0x02,
    FLOCK_CMD_SET_FREQ = 0x03,
    FLOCK_CMD_GET_HOST_BIRD_INFO = 0x04,
    FLOCK_CMD_SET_HOST_BIRD_INFO = 0x05,
    FLOCK_CMD_SET_HOST_POSVEL = 0x06,
    FLOCK_CMD_BROADCAST_DATA = 0x07,
    FLOCK_CMD_SEND_DATA = 0x08,

    FLOCK_CMD_REMOTE_BIRD_INFO = 0x80,
    FLOCK_CMD_REMOTE_BIRD_POSVEL = 0x81,
    FLOCK_CMD_RECV_BROADCAST_DATA = 0x82,
    FLOCK_CMD_RECV_SENT_DATA = 0x83,
} flock_cmd_t;
